### ISSUE TITLE
Small feature requests: direct messages and load message from file

### ISSUE THREAD

**Issue by mh166** [hgrimm/notify_by_webex_teams#1]
Hello,

thank you for this nifty little tool. It helped me a lot with a problem, lately! 😃

I would love to see to features added:
- **Send messages to users directly:** at the moment it seems only possible to message group chats. Judging from the API docs, it shouldn't be too much of a problem.
- **Load message from file:** at the moment im using a batch script to automate the message sending. Something like `notify_by_webex_teams -T ... -t ... -r ... -i < message.txt`. Note that input redirection and the end. It does work... for the time being. 😅 But to be honest: I don't trust this too much. I'd rather be able to load the markdown message from file directly, just like one can upload files.

Unfortunately, I just know enough golang in order to read the source and compile this. Hence this feature request. It would be very nice, should you consider adding these two features. :)

**Comment by hgrimm** [comment]
Hi
I am working on a new version with an additional flag to send direct
messages to a recipient with a email address.

Regards

mh166 ***@***.***> schrieb am Fr. 8. Apr. 2022 um 08:16:

**Comment by hgrimm** [comment]
sending messages to users directly should work now with flag -D

**Comment by mh166** [comment]
Sorry, completely missed to respond: works perfectly! Thanks for the quick help!
